---

apiVersion: "v1"
kind: "Service"
metadata: 
  name: "keycloak-service"
  labels: 
    app: "keycloak"
spec: 
  ports:
    - name: http
      port: 53582
      targetPort: 8080
  selector: 
    app: "keycloak"