---
apiVersion: v1
kind: Service
metadata: 
  name: keycloak-service
  labels:
    app: "keycloak"
spec:
  ports:
    {{- if .Values.service.http.enabled }}
    - name: http
      port:  {{ .Values.service.ports.http  }}
      protocol: TCP
      targetPort: http
    {{- end }}
    {{- if .Values.tls.enabled }}
    - name: https
      port: {{ .Values.service.ports.https }}
      protocol: TCP
      targetPort: https
    {{- end }}
  selector:
    app: "keycloak"