---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Release.Name }}
spec:
  serviceName: {{ .Release.Name }}
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Release.Name }}
  template:
    metadata:
      annotations:
        # Restart pod when config map changes
        # See: https://helm.sh/docs/howto/charts_tips_and_tricks/#automatically-roll-deployments
        checksum/config: {{ include (print $.Template.BasePath "/realm-configmap.yaml") . | sha256sum }}
      labels:
        app: {{ .Release.Name }}
    spec:
    {{- with .Values.image.pullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      volumes: 
        - name: realm-cm-file
          configMap:
            name: {{ .Release.Name }}-configmap
            items:
              - key: myrealm-realm.json
                path: myrealm-realm.json
              - key: myrealm-users-0.json
                path: myrealm-users-0.json
      containers:
      - name: keycloak
        image: {{ template "keycloak.image" . }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        args: ["start-dev --import-realm"]
        env: 
          - name: "KEYCLOAK_ADMIN"
            value: {{ .Values.auth.adminUser }}
          - name: "KEYCLOAK_ADMIN_PASSWORD"
            valueFrom:
              secretKeyRef:
                name: {{ .Release.Name }}-password
                key: password
        ports:
          - name: http
            containerPort: {{ .Values.containerPorts.http }}
            protocol: TCP
          {{- if .Values.tls.enabled }}
          - name: https
            containerPort: {{ .Values.containerPorts.https }}
            protocol: TCP
          {{- end }}
          - name: infinispan
            containerPort:  {{ .Values.containerPorts.infinispan }}
            protocol: TCP
        {{- if .Values.readinessProbe.enabled }}
        readinessProbe: {{- omit .Values.readinessProbe "enabled" | toYaml | nindent 10 }}
          httpGet:
            path: /realms/master
            port: http
        {{- end }}
        volumeMounts:
          - mountPath: /opt/keycloak/data/import
            name: realm-cm-file
        resources:
            {{- toYaml .Values.resources | nindent 12 }}