apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: keycloak
spec:
  serviceName: "keycloak"
  replicas: 1
  selector:
    matchLabels:
      app: keycloak
  template:
    metadata:
      labels:
        app: keycloak
    spec:
    {{- with .Values.image.pullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      volumes: 
        - name: realm-cm-file
          configMap:
            name: keycloak-configmap
            items:
              - key: myrealm-realm.json
                path: myrealm-realm.json
              - key: myrealm-users-0.json
                path: myrealm-users-0.json
      containers:
      - name: keycloak
        image: {{ template "keycloak.image" . }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        args: ["start-dev --import-realm"]
        env: 
          - name: "KEYCLOAK_ADMIN"
            value: {{ .Values.auth.adminUser }}
          - name: "KEYCLOAK_ADMIN_PASSWORD"
            valueFrom:
              secretKeyRef:
                name: keycloak-password
                key: password
        ports:
          - name: http
            containerPort: {{ .Values.containerPorts.http }}
            protocol: TCP
          {{- if .Values.tls.enabled }}
          - name: https
            containerPort: {{ .Values.containerPorts.https }}
            protocol: TCP
          {{- end }}
          - name: infinispan
            containerPort:  {{ .Values.containerPorts.infinispan }}
            protocol: TCP
        {{- if .Values.readinessProbe.enabled }}
        readinessProbe: {{- omit .Values.readinessProbe "enabled" | toYaml | nindent 10 }}
          httpGet:
            path: /realms/master
            port: http
        {{- end }}
        volumeMounts:
          - mountPath: /opt/keycloak/data/import
            name: realm-cm-file